/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation("io.github.wldt:wldt-core:0.4.0")
    implementation("io.github.wldt:mqtt-physical-adapter:0.1.2")
    implementation("io.github.wldt:http-digital-adapter:0.2")
    implementation("io.github.wldt:mqtt-digital-adapter:0.1.2")

    project(":hdt")
}

application {
    // Define the main class for the application.
    mainClass = "org.example.app.AppKt"
}
