services:
  iot_emulation:
    build:
      context: ./iot-emulation
    command: ["./gradlew", "run"]
    depends_on:
      - broker
    environment:
      - MQTT_BROKER=broker
      - MQTT_PORT=1883
      - MQTT_TOPIC="sensor/blood-pressure"

  digital_twin:
    build:
      context: ./digital-twin-wldt
    command: ["./gradlew", "run"]
    depends_on:
      - broker
    environment:
      - MQTT_BROKER=broker
      - MQTT_PORT=1883

  broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config

  frontend:
    build:
      context: ./frontend
    command: ["npm", "start"]
    ports:
      - "3000:3000"
    stdin_open: true         # optional, helps with interactive dev tools
    tty: true                # optional, helps with React developmentc
